### PR TITLE
Add relationships and attributes, update tests

### PR DESCRIPTION
**Pull request by pronebird**
Opening this PR upon your request. Please, note that this PR needs to be refined since certain tests fail.

### CODE REVIEW

**Comment by tommikaikkonen** [comment]
Once again, thank you for your efforts here. I based my implementation of this in #62 based on what you wrote here. Instead of a `defaultValue` I put in an optional `getDefault` function, where you can pass `() => 'myDefaultValue'` if it's a constant value. I'll probably add the `AttributeDescriptor` in, too - it'll be cleaner than my current code.

Some differences: if you pass an object with keys that are not defined as fields, an error is raised. I think this will catch bugs early for a lot of people.

With the non-relationship attributes, it should be easier for people to build extra functionality and validation on top of Redux-ORM -- something similar to `redux-orm-proptypes`, which needs some updating after React deprecated those APIs. I think this is a good step forward.

**Comment by pronebird** [comment]
@tommikaikkonen thanks! Agreed with all of the above.

**Comment by pronebird** [comment]
Closing since this was incorporated into #62

**Comment by plandem** [comment]
for validation i'm using this:
```
https://github.com/yiminghe/async-validator
```

maybe it will help

**Comment by markerikson** [comment]
@tommikaikkonen : Side question - what do you mean by "React deprecated those APIs"?  If you're talking about `React.PropTypes`, the React team is definitely encouraging the use of Flow overall, but `PropTypes` aren't actually "deprecated" that I know of.

**Comment by pronebird** [comment]
@markerikson https://facebook.github.io/react/warnings/dont-call-proptypes.html

**Pull request closed without merging**
