### PR TITLE
Fix #53 by using a Reflect.construct based inheritance mechanism

### LINKED ISSUE #53: Getting error "Class constructor Record cannot be invoked without 'new'"
Hello,

Just trying out redux orm and I am getting the following error after a basic Model.create

```
TypeError: Class constructor Record cannot be invoked without 'new'

  at new SessionBoundModel (../node_modules/redux-orm/lib/Session.js:77:124) <-- redux-orm internal
  at Function.create (../node_modules/redux-orm/lib/Model.js:663:28) <-- session.Record.create
  at Object.RECORD_ADDED (state/orm/models.js:39:16) <-- event inside Record.reducer
  at Function.reducerForRecord [as reducer] (state/orm/models.js:63:28)  <-- Record.reducer
```

Here is my model:

``` javascript
// My domain is a database; record is a row which has many fields; fields can
// be of many types but they only exist in the context of a record; if a record is deleted
// fields must also be deleted.

export class Record extends Model {}

Record.modelName = 'Record'

Record.fields = {
  fields: many('Field')
}

// Please note that makeReducer() isn't doing anything fancy; just matches event.type
// to each specific function and passes session as third argument instead of the model class   
// Error is same if reducer is written with a switch statement
Record.reducer = makeReducer(Record, {

  [events.RECORD_ADDED] (state, event, session) {
    session.Record.create({ id: event.id })    // <--- this is where the error occurs
  },

  [events.FIELD_ADDED] (state, event, session) {
    session.Record.withId(event.record).fields.add(event.id)
  },

  [events.FIELD_REMOVED] (state, event, session) {
    const field = session.Field.withId(event.id)
    const record = session.Record.withId(field.record)

    record.fields.remove(event.id)
  }

})
```

This also happens with other models (for instance the `Field` model referenced above). I also tried installing redux-orm v0.8.3 version to see if this was a regression.

Since all the examples show the `create` static method being called to initialize models,  I have not tried attempted to call new directly.

Hope that is clear, let me know if you need more info.

Thanks for the package; I hope it will be useful.

### PR DESCRIPTION
**Pull request by haveyaseen**

### CODE REVIEW

**Comment by plandem** [comment]
i’m quite sure Reflect will decrease performance, i would check. this is not solution that we trying to get here and with with worse output - no reason to use. but need to check how bad is it?!

**Comment by haveyaseen** [comment]
Yes, it does indeed seem to decrease performance :disappointed: Averages of 10 measurements:

| | Creating 10000 objects           | Looking up 10000 objects  | Adding 2500 relations | Performing 500 queries | Removing 1000 relations  |
| ------------- |-------------:| -----:| -:| -:| -:|
| `extends`    | 0.3319s | 0.2015s | 2.5097s | 2.0617s | 2.6538s |
| `Reflect.construct`      | 0.4171s | 0.3038s | 2.5339s | 2.2178s | 2.7749s |
| delta     | +85.2ms | +102.3ms | +24.2ms | +156.1ms | +121.1ms |
| delta per obj/rel     | +0.009ms | +0.01ms | +0.01ms | +0.31ms | +0.12ms |

We cannot ignore the bug either, though. How about a compromise of making a new minor release (instead of a patch) and aiming to replace the solution by a more performant one?

**Comment by plandem** [comment]
`How about a compromise of making a new minor release (instead of a patch) and aiming to replace the solution by a more performant one?`

What do you mean?

**Comment by haveyaseen** [comment]
I'm saying our users need a fix for their problem, and that would normally mean releasing a version 0.11.1. This would mean worse performance for everyone who set their version constraint to 0.11.x.
If we instead release a version 0.12.0, then those users will not accidentally incorporate performance degradations for no reason, and those who need the fix can use v0.12.0.

**Comment by plandem** [comment]
does this patch really fix problem? I actually never had any issues here, so not sure. I saw tests, is it reproducible?

**Comment by plandem** [comment]
But I'm for "minor version" and would be nice to write about that and performance decrease in changelog.

I will try to spend some time on weekends and revise session, maybe I will get solution. That part was second that was most annoying for me.

**Comment by haveyaseen** [comment]
Yes, it is reproducible and this patch fixes the problem.
See https://travis-ci.org/haveyaseen/redux-orm/jobs/398190734.

image

**Comment by haveyaseen** [comment]
Great to hear :slightly_smiling_face:  It would be interesting to see an alternative solution to the problem.

**Comment by plandem** [comment]
I'm not sure yet, but meanwhile - let's publish a minor version

**Pull request merged**
