### PR TITLE
tiny changes

### PR DESCRIPTION
**Pull request by plandem**
*up deps
+added upsert method to Model

### CODE REVIEW

**Comment by carlesnunez** [comment]
IMHO this shouldn't be merged as u did. There was an open PR with a person that invests they time to make it work. If we start to take another one 'ideas' or proposals putting them on master just because you can and that person not would demotivate the people to make PR's proposing changes because they wouldn't appear never as a contributors cause their ideas won't be implemented by themselves....

Is not about my work, is about the idea to have one people thinking ways to improve the library and another person taking this ideas and putting on master directly cause he can

Is just my opinion 😞

**Comment by plandem** [comment]
1) PR that you mentioned has multi issues

2) there was a request to revert formatting to review changes( that I'm totally agree) for a quite long time without any response/feedback.

3) my commit mainly patches "system" files and add the "upsert" feature that had some positive feedback about naming at original issue and has very simple implementation that already mentioned few times at others issues/comments. So I don't see any problem here.

P.s. It's all about contributing to library and improving it, but not about personal ego and copyrighting every line of code. As for me, I would be fine with such merging.

**Comment by tiii** [comment]
Unfortunately you did not provide tests for the upsert method, I don't think we should start to introduce untested functionality.

How about adding a CI-Service (e.g. travis ci, circle ci) to the library for linting the project und running the tests, so a commiter gets (nearly) instant feedback on potential flaws. I am using circle ci on most of my projects and setting this up is a no-brainer, also they are free for open-source projects. Maybe we could also add a code coverage check, to make sure coverage doesn't drop (adding untested functionality)

**Comment by carlesnunez** [comment]
@plandem seems that you didn't understand a single line of what I wrote. Im not trying to entry on a ego war or something like that. Im just saying that is not a good practice introduce code without tests and make any PR to consult the community about that even if it's a feature that was requested by one of you're mates. Considering that this is your FIRST contribution to that project you should take notes and just be empathic about what you did. Just that.

For the next time you should ask the PR owner before do movements on the project cause is our project not just yours 👍

**Comment by plandem** [comment]
@tiii you are right, will add tests. +1 for CI and coverage. About linting - I added pre-commit hook to lint, but it's only a temp. solution till CI. I have no experience with circle CI, but was using travis ci at github with code coverage.

**Comment by plandem** [comment]
@carlesnunez 

1) your original message has no any word about tests.  And I'm fine about tests - we should cover as much as possible.

2) yes, it's first commit, but not first contribution to this project. I'm not a newbie here. 

3) about **asking PR owner** - I already wrote my vision - owner was requested to revert formatting to do code review about changes. After that no answer or feedback from **owner** for a quite long time. Code review is a common practice in any mature project/team. So...how long must we wait  for reaction of owner(at least with feedback) to move forward with basic feature?

I have nothing to add here - test will be added later as updates for documentation.

**Comment by plandem** [comment]
@tiii 

ok, I revert changes about upsert. Synced **develop** branch and merged this feature to updated develop. Let's stick to *git-flow* pattern as before.

**Comment by tiii** [comment]
👍

In my experience Circle CI has less wait time before your test get executed and no setup if you just want to execute the npm test command. But I did not use travis for the last 2 years so maybe this got better :D I think the only thing that really matters is a proper github integration. 😉

**Comment by plandem** [comment]
@tiii @tommikaikkonen 
well, I added all required settings to this branch:
https://github.com/tommikaikkonen/redux-orm/tree/feature/jest

Another branch, because I also migrate tests to jest. Not sure that everybody will be fine about it. But it's easy to setup.

**Comment by tiii** [comment]
@plandem great work! you could open a new PR for it just even if its wip?

**Comment by plandem** [comment]
well. it's not wip (at least looks like everything is done), but need to integration (by repo owner) at travis and codecov

**Comment by plandem** [comment]
@tiii Right now I'm not sure about our **workflow**. I'm fine with git-flow, but for me it's not a clear who will merge PR to dev and when to decide that feature must be merged?!

**Comment by tiii** [comment]
Yeah, I think we didn't figure this out yet. I would suggest we open a PR and then request reviews from each other? I prefer having at least another person take a look at my code before merging it.

I'm fine with using git-flow too, i think it's time for a how to contribute doc. 😉

**Comment by plandem** [comment]
My english is not so fluent, so I will try to stay away from docs :)

I would use github feature issue/pr template.

I added for PR:
https://github.com/tommikaikkonen/redux-orm/blob/master/.github/PULL_REQUEST_TEMPLATE.md

but we also can create for issue:
https://github.com/tommikaikkonen/redux-orm/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by carlesnunez** [comment]
As I work on my current company we just open one PR ask for review one or two mates and once they say OK we merge the feature. Nice work @plandem BTW

**Pull request merged**
