### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by haveyaseen**
With these changes `npm audit` now returns 0 vulnerabilities.

**Major updates:**
- Webpack v4
  - [x] add `webpack-cli`, `webpack-merge`
  - [x] update `webpack.config.js` 
  - [x] split up `webpack.config.js` into `webpack.common.js`, `webpack.prod.js` and `webpack.dev.js`
  - [x] remove `cross-env`
- ~~Babel v7 (beta)~~
  - [x] ~~update `.babelrc`~~
- ESLint v4 along with new rules in `eslint-config-airbnb-base` v12
  - [x] fix `prefer-destructuring` errors
  - [x] disable `function-paren-newline`
- Gulp v4
  - [x] test docs/dist uploading
  - [x] circumvent shinnn/gulp-gh-pages#116
- Jest v23
  - [x] add `jest-cli`
  - [x] remove `babel-jest`
- Codecov v3

### CODE REVIEW

**Comment by haveyaseen** [comment]
Would highly appreciate comments on whether or not upgrading to Babel 7 is something we should do. This means requiring users to use Babel 7 when they want to transpile the source themselves.

**Comment by plandem** [comment]
i’m against beta version of any software   in production

**Comment by haveyaseen** [comment]
@plandem Alright, I have reversed the upgrade to Babel v7. Fortunately `npm audit` does not complain either way :slightly_smiling_face: Especially given that it seemingly won't take much longer for a stable v7 of Babel to be released, we can just as well wait for it.

Just need to confirm that Gulp still works, then I think this PR is ready to be merged.

**Comment by plandem** [comment]
actually i would remove gulp, we already have webpack. i also tried to replace it with rollup, but had some issues with external lib here. anyway it was before webpack4, so probably no need anymore

**Comment by haveyaseen** [comment]
Yes, I agree it would be a good step to remove Gulp. `gulp-gh-pages` doesn't seem to maintained a lot, we may be able to find a better alternative to push the docs and bundles.

However let's leave that for another PR, this one is already more than complex enough.

**Comment by haveyaseen** [comment]
I'll go ahead and merge this so we can work on transpiling to ES2017 in a sane way.

**Comment by markerikson** [comment]
Hijacking the thread a bit: @haveyaseen , just wanted to say thanks for taking over active maintainership of Redux-ORM!  We're using it in one of our apps (and I hope to eventually use it in the other one), but we're wrapping up a dev cycle atm and it'll be a while before we're adding new code that specifically uses Redux-ORM.  Meanwhile, I'm more than fully occupied doing stuff as a Redux maintainer.  So, while I still have a vested interest in Redux-ORM, I definitely don't have time to actively work on it myself.  It's great to see that someone else is both interested and willing to push the library forward.

**Comment by plandem** [comment]
yeah. sadly i’m not involved anymore at any project that uses redux-orm, so right now probably can’t contribute a lot.

**Comment by haveyaseen** [comment]
Alright guys :smile: Actually both of you have done fantastic jobs so far, so I have to thank you for that as well!

As for myself, I don't expect to be working on Redux-ORM all too meticulously. But it would be extremely sad for the library to die off due to a lack of maintenance. It must retain its high quality and stay up-to-date and secure. These are the most important requirements and I'll do my best to accomplish that. 

Everything else comes afterwards. Yet Redux-ORM can only have a bright feature if it becomes more user-friendly and attractive for contributors, both quite hard things to do when developing a database-like system. I am more than happy that Redux exists and that you and others put so much effort into it. Just by itself, it is hardly enough for big applications, though. The simple state management that this project provides is unique and essential for developers who need to get up and running quickly. And they are my motivation for doing this.

**Pull request merged**
